### ISSUE TITLE
Add article sharing

### ISSUE THREAD

**Issue by shakiroye** [jackamrl/worldwile-news-app#21]
The purpose of this issue is to propose a new feature, article sharing. Currently, the website allows users to browse and read articles, but lacks the capability to easily share articles with others.

**Comment by jackamrl** [comment]
> The purpose of this issue is to propose a new feature, article sharing. Currently, the website allows users to browse and read articles, but lacks the capability to easily share articles with others.

Thanks. I think that will be the new feature.
